apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    component: mongodb
    project: roboshop
    tier: database
spec:
  replicas: 1
  selector:
   matchLabels:
    component: mongodb
    project: roboshop
    tier: database
  template:
    metadata:
      labels:
        component: mongodb
        project: roboshop
        tier: database
    spec:
      containers:
      - name: nginx
        image: nginx:stable-perl
---
apiVersion: v1
kind: Service
metadata: 
  name: mongodb
  labels:
    component: mongodb
    project: roboshop
    tier: database
spec:
  type: LoadBalancer
  selector:
    component: mongodb
    project: roboshop
    tier: database
  ports:
    - protocol: TCP
      port: 27017 # service port
      targetPort: 27017 # container port
